### ISSUE TITLE
LINQKit does not support referencing expressions stored in properties (InvalidCastException)

### ISSUE THREAD

**Issue by poizan42** [scottksmith95/LINQKit#124]
Running the following program:

```CSharp
using System;
using System.Linq.Expressions;
using LinqKit;

namespace Test
{
    class Program
    {
        public static Expression<Func<int, int>> Foo => x => x * 6;

        static void Main(string[] args)
        {
            Expression<Func<int, int>> bar = x => Foo.Invoke(x * 7);
            Expression<Func<int, int>> barExpanded = bar.Expand(); // <-- System.InvalidCastException
            Console.WriteLine(barExpanded.Invoke(1));
        }
    }
}
```

Fails with

```
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.PropertyExpression' to type 'System.Linq.Expressions.LambdaExpression'.
   at LinqKit.ExpressionExpander.VisitMethodCall(MethodCallExpression m) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionExpander.cs:line 78
   at LinqKit.ExpressionVisitor.Visit(Expression exp) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionVisitor.cs:line 71
   at LinqKit.ExpressionVisitor.VisitLambda(LambdaExpression lambda) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionVisitor.cs:line 353
   at LinqKit.ExpressionVisitor.Visit(Expression exp) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionVisitor.cs:line 73
   at LinqKit.Extensions.Expand[TDelegate](Expression`1 expr) in C:\projects\LINQKit\src\LinqKit.Core\Extensions.cs:line 54
   at Test.Program.Main(String[] args) in C:\projects\LINQKit\Test\Program.cs:line 14
```

This may be related to #89 where it's a delegate rather than an expression in a property that causes problems.

**Comment by sdanyliv** [comment]
@StefH, I think It should be fixed in #126

**Comment by StefH** [comment]
Hello @sdanyliv, thanks for noticing.

If you have time, can you add an extra UnitTest for this scenario? If this is green, then I can close this issue.

**Comment by StefH** [comment]
@poizan42 : Can you please try `1.1.20-preview-01` version in NuGet to see if this fixes your issue?

**Comment by poizan42** [comment]
It fixes the case I wrote in this issues. But it does not work with deeper nesting, e.g. the test [ExpressionCombiner_ExpressionAsProperty_FromExpressionVariable](https://github.com/poizan42/LINQKit/blob/b81b20e6be66cf62f42f6e1df44e8bc296a199b7/tests/LinqKit.Tests.Net452/ExpressionCombinerTests.cs#L106) still fails.

**Comment by sdanyliv** [comment]
Updated PR https://github.com/scottksmith95/LINQKit/pull/127 with fix.

**Comment by StefH** [comment]
PR is merged.
